In [1]:
import numpy as np


### Trace off 5x5 matrix

In [52]:
np.random.seed(420)
A = np.random.rand(5,5)
trace = np.trace(A)
np.einsum("ii", A) == trace

True


### matmul off 5x5 matrix and 5x1 vector

In [45]:
np.random.seed(420)
A = np.random.rand(5,5)
b = np.random.rand(5)
correct = np.matmul(A, b)
correct

array([0.58218068, 0.89356058, 0.41321594, 0.70373773, 0.83772429])

In [51]:
ein = np.einsum("ji,i", A, b)
print(ein)
np.allclose(ein, correct)

[0.58218068 0.89356058 0.41321594 0.70373773 0.83772429]


True

### Vector outer product

In [57]:
np.random.seed(420)
a = np.random.rand(5)
b = np.random.rand(5)
correct = np.outer(a, b)
print(correct)

[[0.19877123 0.11127109 0.02131797 0.19770501 0.18896485]
 [0.28528634 0.15970179 0.0305966  0.28375603 0.27121173]
 [0.16812635 0.09411624 0.01803134 0.1672245  0.15983183]
 [0.06859518 0.03839922 0.00735675 0.06822723 0.06521104]
 [0.54670919 0.30604493 0.05863388 0.54377659 0.51973729]]


In [58]:
ein = np.einsum('i,j->ij', a, b)
print(ein)
np.allclose(ein, correct)

[[0.19877123 0.11127109 0.02131797 0.19770501 0.18896485]
 [0.28528634 0.15970179 0.0305966  0.28375603 0.27121173]
 [0.16812635 0.09411624 0.01803134 0.1672245  0.15983183]
 [0.06859518 0.03839922 0.00735675 0.06822723 0.06521104]
 [0.54670919 0.30604493 0.05863388 0.54377659 0.51973729]]


True